server:
  port: 8081 # 端口号
netty:
  port: 18081 # netty端口
  bossGroupThread: 8  # netty中Boss线程数
  workerGroupThread: 16   # netty中 worker线程数
  webSocketPath: /nettyWeb   # netty中开启ws连接uri
spring:
  application:
    name: nettyWeb  # 实例名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: '031027'
        port: ${netty.port}
  data:
    redis:  # redis
      host: 101.201.47.132
      port: 6379
      password: '031027'
      jedis:
        pool: # 缓存池
          enabled: true
          max-active: 4
          min-idle: 1
rocketmq:
  name-server: 192.168.14.136:9876
  producer:
    group: boot-group        # 生产者组别
    send-message-timeout: 3000  # 消息发送的超时时间
    retry-times-when-send-async-failed: 2  # 异步消息发送失败重试次数
    max-message-size: 4194304       # 消息的最大长度