server:
  port: 8082
spring:
  application:
    name: msgHandler
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: '031027'
  data:
    redis:
      host: 101.201.47.132
      port: 6379
      password: '031027'
      jedis:
        pool:
          enabled: true
          max-active: 4
          min-idle: 1
dubbo:
  protocol:
    name: dubbo
    port: 28082
  application:
    name: msgHandler
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: '031027'