server:
  port: 8082
spring:
  application:
    name: msgHandler
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: '031027'
  data:
    redis:
      host: 101.201.47.132
      port: 6379
      password: '031027'
      jedis:
        pool:
          enabled: true
          max-active: 4
          min-idle: 1
dubbo:
  protocol:
    port: 28082
    name: dubbo
  application:
    name: msgHandlerDubbo
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: '031027'
rocketmq:
  name-server: 192.168.14.136:9876
  producer:
    group: msg-provider       # 生产者组别
    send-message-timeout: 3000  # 消息发送的超时时间
    retry-times-when-send-async-failed: 2  # 异步消息发送失败重试次数
    max-message-size: 4194304       # 消息的最大长度
